ls => list all the files that are in the folder where i am;
cd => get inside the file i want;
ctrl + l => clear the console;
cd .. => goes up one level in the root;
pwd => shows me where i am, present working directory
cd => going to the root
mkdir => creates a directory
cp => copy the file => cp namefile destinationfile(can create a file also)
cp -r => copy the directoty => same as cp
rm => delete the file
rm - r => delete the directory
mv => move the name of one file to other=> move file.txt files.txt => file is now files.txt




